### ISSUE TITLE
Trouble with target=graylog

### ISSUE THREAD

**Issue by YamilBracho** [dustinchilson/NLog.Targets.GraylogHttp#13]
Hi
I just trying to send some information to GrayLog. I wrote in my NLog.config this :+1: 
`<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <extensions>
    <add assembly="NLog.Targets.GraylogHttp"/>
  </extensions>
  <targets>
    <target name="console" xsi:type="Console" />
    <target name="graylog"
              xsi:type="GraylogHttp"
              facility="Myfacility"
              graylogServer="99.99.99.99"
              graylogPort="99999" />
  </targets>
  <rules>
    <logger name="*" minlevel="Debug" writeTo="console" />
    <logger name="*" minlevel="Debug" writeTo="graylog" />
  </rules>
</nlog>
`

But Visual Studio complains on line <target name="graylog" and tooltip with error message "This is an invalid xsi:type "http://www.nlog-project.org/schemas/Nlog.xsd:GraylogHttp"

Is there a way to turn off this validation ? or is it  something missing ?

TIA,
Yamil

**Comment by YamilBracho** [comment]
Hi
I add some debugging properties to my NLog config files and now I got
2018-07-12 10:18:24.6060 Error GraylogHttp Target[graylog]: Error initializing target Exception: System.UriFormatException: Invalid URI: The URI scheme is not valid.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at NLog.Targets.GraylogHttp.GraylogHttpTarget.InitializeTarget()
   at NLog.Targets.Target.Initialize(LoggingConfiguration configuration)
2018-07-12 10:18:24.6671|DEBUG|NetFrameworkApp.Program|[Message=Test Log Error - NetFrameWork][Brand=AMBERCORENA][PayLoad={ Name = Pepe Trueno, Age = 35 }][AuditLogin=System]

Any hint to solve this 
Regards,
Yamil

**Comment by dustinchilson** [comment]
The xsi error can be ignored, https://stackoverflow.com/a/39311279.

You've got a couple issues..

The first is your exception which is caused by "graylogServer="99.99.99.99"" this needs to be changed to "graylogServer="http://99.99.99.99"" or https:// depending on if you have TLS enabled.

Also port 99999 is higher than what is possible, 65535 is the max port.

**Comment by YamilBracho** [comment]
Thanks dustin
I wrote 99.99.99.99 to hide my real server address :-)

Let me check again and thanks a lot!!!

**Comment by YamilBracho** [comment]
Now I got this message

2018-07-12 15:03:51.2897 Error Parsing configuration from C:\Users\yamil\source\repos\TestNLog\NetFrameworkApp\bin\Debug\NLog.config failed. Exception: NLog.NLogConfigurationException: Exception when parsi
ng C:\Users\yamil\source\repos\TestNLog\NetFrameworkApp\bin\Debug\NLog.config.  ---> System.NotSupportedException: Parameter value not supported on TargetPropertyWithContext
   at NLog.Internal.PropertyHelper.SetPropertyFromString(Object obj, String propertyName, String value, ConfigurationItemFactory configurationItemFactory)
   at NLog.Config.XmlLoggingConfiguration.ConfigureObjectFromAttributes(Object targetObject, NLogXmlElement element, Boolean ignoreType)
   at NLog.Config.XmlLoggingConfiguration.AddArrayItemFromElement(Object o, NLogXmlElement element)
   at NLog.Config.XmlLoggingConfiguration.SetPropertyFromElement(Object o, NLogXmlElement element)
   at NLog.Config.XmlLoggingConfiguration.ParseTargetElement(Target target, NLogXmlElement targetElement, Dictionary`2 typeNameToDefaultTargetParameters)
   at NLog.Config.XmlLoggingConfiguration.ParseTargetsElement(NLogXmlElement targetsElement)
   at NLog.Config.XmlLoggingConfiguration.ParseNLogElement(NLogXmlElement nlogElement, String filePath, Boolean autoReloadDefault)
   at NLog.Config.XmlLoggingConfiguration.ParseTopLevel(NLogXmlElement content, String filePath, Boolean autoReloadDefault)
   at NLog.Config.XmlLoggingConfiguration.Initialize(XmlReader reader, String fileName, Boolean ignoreErrors)
   --- End of inner exception stack trace ---
2018-07-12 15:03:51.3067 Warn Failed loading config from C:\Users\yamil\source\repos\TestNLog\NetFrameworkApp\bin\Debug\NLog.config. Invalid XML?

And my NLog config file is 

<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      internalLogToConsole="true" 
      internalLogLevel="Warn" >

  <extensions>
    <add assembly="NLog.Targets.GraylogHttp"/>
  </extensions>
  <targets>
    <target name="console" xsi:type="Console" />
    
    <target name="graylog"
            xsi:type="GraylogHttp"
            facility="MyFacility"
            graylogServer="http://MyServerIP"
            graylogPort="12201">
      <parameter name="AdditionalFields" value="app:AMBERCORENA,version:2.0,Environment:DEV,Level:DEBUG" />
    </target>
  </targets>

  <rules>
    <logger name="*" minlevel="Debug" writeTo="console" />
    <logger name="*" minlevel="Debug" writeTo="graylog" />
  </rules>
</nlog>

**Comment by YamilBracho** [comment]
Ok
It seems it does not support the parameter value or name I added so i commented out and re run and i got 

2018-07-12 15:14:35.3416|DEBUG|NetFrameworkApp.Program|[Message=Test Log Error - NetFrameWork][Brand=AMBERCORENA][PayLoad={ Name = Pepe Trueno, Age = 35 }][AuditLogin=System]
2018-07-12 15:14:36.7150 Error GraylogHttp(Name=graylog): Fail to post LogEvents Exception: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException:
Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 172.20.6.37:12201
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exceptio
n)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---

maybe is it a UDP addr ?

**Comment by YamilBracho** [comment]
No, as you said only http y https are allowable. But I got the same error message
"No connection could be made because the target machine actively refused "

**Comment by dustinchilson** [comment]
What input is on port 12201 of your Graylog server. It needs to be the Gelf HTTP one.

**Comment by YamilBracho** [comment]
Dustin, I am afraid it is UDP ...
Do you know a UPD library to connect to GrayLog ?

**Comment by dustinchilson** [comment]
I've seen a couple, I've not used them much.

For NLog
https://github.com/2020Legal/NLog.Targets.Gelf
https://github.com/Pliner/EasyGelf

I'm a fan of this one if you're willing to switch over to Serilog
https://github.com/whir1/serilog-sinks-graylog

**Comment by YamilBracho** [comment]
Thanks a lot!!!!
Let me check them and then share some comments

Regards,
Yamil

**Comment by YamilBracho** [comment]
Dustin, I test with NLog.targets.gelf and works fin in .Net FrameWork and .NetCore.
I heartly appreciate your help and support.
Best regards,
Yamil

**Comment by snakefoot** [comment]
@YamilBracho You can also use [NLog.GelfLayout](https://www.nuget.org/packages/NLog.GelfLayout)

Then you can use UDP / TCP / HTTP as you like. See config examples here:

https://github.com/farzadpanahi/NLog.GelfLayout
