### ISSUE TITLE
Option to avoid errors if the host isn't known

### ISSUE THREAD

**Issue by joaopalma5** [dustinchilson/NLog.Targets.GraylogHttp#197]
Hello,

In my case I want avoid errors if the host isn't known, now I have this Error in runtime:
HttpRequestException: No such host is known. (graylogq:80)

I want ignore all errors if server is unavailable, it's possible?

Thanks

**Comment by dustinchilson** [comment]
What version of the Library are you using?

https://github.com/dustinchilson/NLog.Targets.GraylogHttp/blob/f186822690298e9f56c6ce34c0a374e858ff32bc/src/NLog.Targets.GraylogHttp/GraylogHttpTarget.cs#L71

and 

https://github.com/dustinchilson/NLog.Targets.GraylogHttp/blob/f186822690298e9f56c6ce34c0a374e858ff32bc/src/NLog.Targets.GraylogHttp/GraylogHttpTarget.cs#L146

Should have caught that error.  I can try and test this to see if it's not for some reason.

**Comment by joaopalma5** [comment]
Helllo, 

I'm using Nlog.Targets.GraylogHttp V2.0.0 from NuGet package manager.
[print screen](https://ibb.co/02zbvWB)

Error messages:
System.AggregateException: 'One or more errors occurred. (No such host is known. (graylogq:80))'
HttpRequestException: No such host is known. (graylogq:80)
SocketException: No such host is known.

Details:
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (No such host is known. (graylogq:80))
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at NLog.Targets.GraylogHttp.GraylogHttpTarget.<>c__DisplayClass45_0.<Write>b__0()
   at Polly.Policy.<>c__DisplayClass114_0`1.<Execute>b__0(Context ctx, CancellationToken ct)
   at Polly.CircuitBreaker.CircuitBreakerPolicy.<>c__DisplayClass8_0`1.<Implementation>b__0(Context ctx, CancellationToken ct)
   at Polly.CircuitBreaker.CircuitBreakerEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldHandleExceptionPredicates, ResultPredicates`1 shouldHandleResultPredicates, ICircuitController`1 breakerController)
   at Polly.CircuitBreaker.CircuitBreakerPolicy.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`1 action)
   at NLog.Targets.GraylogHttp.GraylogHttpTarget.Write(LogEventInfo logEvent)
   at NLog.Targets.Target.Write(AsyncLogEventInfo logEvent)
   at NLog.Targets.Target.WriteAsyncThreadSafe(AsyncLogEventInfo logEvent)
   at NLog.Targets.Target.WriteAsyncLogEvent(AsyncLogEventInfo logEvent)
   at NLog.LoggerImpl.WriteToTargetWithFilterChain(Target target, FilterResult result, LogEventInfo logEvent, AsyncContinuation onException)
   at NLog.LoggerImpl.Write(Type loggerType, TargetWithFilterChain targetsForLevel, LogEventInfo logEvent, LogFactory factory)
   at NLog.Logger.WriteToTargets(LogEventInfo logEvent, TargetWithFilterChain targetsForLevel)
   at NLog.Logger.WriteToTargets(LogLevel level, Exception ex, String message, Object[] args)
   at NLog.Logger.Error(Exception exception, String message)

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
HttpRequestException: No such host is known. (graylogq:80)

Inner Exception 2:
SocketException: No such host is known.

**Comment by dustinchilson** [comment]
This should be fixed, Pushed a new release and nuget package. Might take a few for Nuget.org to index it

https://github.com/dustinchilson/NLog.Targets.GraylogHttp/releases/tag/v2.0.1

**Comment by joaopalma5** [comment]
Thanks, @dustinchilson !!
