### ISSUE TITLE
FallbackGroup doesn't select further targets after GraylogHttp exceptions

### ISSUE THREAD

**Issue by MaksimKneller** [dustinchilson/NLog.Targets.GraylogHttp#199]
When graylogServer host is unavailable, I'd like to log to the Console. A FallbackGroup target would be ideal. In the example below, the GraylogHttp target times out after 20s. However, the Console target is never reached.

Using NLog.Targets.GraylogHttp nuget package 2.0.1 with .NET Core 3.1

**NLog.config**
```
<?xml version="1.0" encoding="utf-8" ?>
<nlog 
      
      xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd">
  <extensions>
    <add assembly="NLog.Targets.GraylogHttp"/>
  </extensions>
  <targets>

    <target xsi:type="FallbackGroup" name="GrayFallback" returnToFirstOnSuccess="false">

      <target name="GrayServer"
                xsi:type="GraylogHttp"
                facility="Test"
                graylogServer="http://XXXX:12201">
      </target>

      <target name="Console" xsi:type="Console"  layout="${longdate} ${callsite} ${level} ${message}"/>

    </target>

  </targets>

  <rules>
    <logger name="*" minlevel="Trace" writeTo="GrayFallback"/>
  </rules>

</nlog>

```

**Program.cs**
```
using NLog;
using System;
using System.Diagnostics;

namespace GrayLogTester
{
    class Program
    {
        static void Main(string[] args)
        {
            var nLogger = LogManager.GetCurrentClassLogger();
            var e = new LogEventInfo(LogLevel.Trace, "Test", "Testmsg");
            
            Console.WriteLine("Logging 1");
            nLogger.Log(e);

            Console.WriteLine("Logging 2");
            nLogger.Log(e);

            Console.Read();
        }
    }
}

```

**Enabled internal logging afterwards to get the full error:**
```
Logging 1
2021-03-05 01:28:48.2801 Error GraylogHttp(Name=GrayServer): Graylog server error, the log messages were not sent to the server. Exception: System.AggregateException: One or more errors occurred. (No such host is known.)
 ---> System.Net.Http.HttpRequestException: No such host is known.
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at NLog.Targets.GraylogHttp.GraylogHttpTarget.<>c__DisplayClass45_0.<Write>b__0()
   at Polly.Policy.<>c__DisplayClass126_0`1.<ExecuteAndCapture>b__0(Context ctx, CancellationToken ct)
   at Polly.CircuitBreaker.CircuitBreakerPolicy.<>c__DisplayClass8_0`1.<Implementation>b__0(Context ctx, CancellationToken ct)
   at Polly.CircuitBreaker.CircuitBreakerEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldHandleExceptionPredicates, ResultPredicates`1 shouldHandleResultPredicates, ICircuitController`1 breakerController)
   at Polly.CircuitBreaker.CircuitBreakerPolicy.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Wrap.PolicyWrapEngine.<>c__DisplayClass3_0`1.<Implementation>b__0(Context ctx, CancellationToken ct)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
Logging 2
2021-03-05 01:28:53.8606 Error GraylogHttp(Name=GrayServer): Graylog server error, the log messages were not sent to the server. Exception: System.AggregateException: One or more errors occurred. (No such host is known.)
 ---> System.Net.Http.HttpRequestException: No such host is known.
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at NLog.Targets.GraylogHttp.GraylogHttpTarget.<>c__DisplayClass45_0.<Write>b__0()
   at Polly.Policy.<>c__DisplayClass126_0`1.<ExecuteAndCapture>b__0(Context ctx, CancellationToken ct)
   at Polly.CircuitBreaker.CircuitBreakerPolicy.<>c__DisplayClass8_0`1.<Implementation>b__0(Context ctx, CancellationToken ct)
   at Polly.CircuitBreaker.CircuitBreakerEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldHandleExceptionPredicates, ResultPredicates`1 shouldHandleResultPredicates, ICircuitController`1 breakerController)
   at Polly.CircuitBreaker.CircuitBreakerPolicy.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Wrap.PolicyWrapEngine.<>c__DisplayClass3_0`1.<Implementation>b__0(Context ctx, CancellationToken ct)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)

```

**Comment by dustinchilson** [comment]
I've never used the fallback group target. But if it depends on a thrown exception the graylog target would never trigger it because it eats all exceptions and logs them to the internal log.

In general I configure to log to both graylog and console all the time with different minlevels.

What purpose would a fallback to console do in your use case?

**Comment by MaksimKneller** [comment]
Thank you for letting me know re greedy exception handling. Here the console target was just for testing. In the actual project the fallback would use a local or NAS File target serving as a backup in case the graylog server is down. There will be too many logs for writing to graylog + File simultaneously the whole time, which is why the File would kick in only in a fallback/disaster scenario. 

Do you have any recommendations for handling host unavailability when using GraylogHttp target?

Alternatively, is there a mechanism already in place to alter the default behavior and allow exceptions to bubble up?
